<?php 
	include 'header.php';
?>

<h1>Description de la guilde</h1>

Date de cr&#xE9;ation : 11 mars 2006<br/>
Nombre de membres : une soixantaine <br/>
Maitre de guilde : A l&#x2019;origine la guilde a &#xE9;t&#xE9; cr&#xE9;&#xE9;e par deux amis : Dark Boudha et Shining Boudha, ils ont laiss&#xE9; le poste de MG &#xE0; Aramyna Del Wylred le 20 novembre 2007.<br/>
Objectifs : S&#x2019;amuser sans prise de t&#xEA;te. La guilde est essentiellement pve mais depuis quelque temps elle se tourne un peu vers le pvp pour devenir une guilde mixte. <br/>
<br />
<h1>Histoire RP</h1><p><strong>Chapitre premier : la naissance des disciples de Baal ou la rencontre des 2 Boudhas</strong><br />
  <br />
Tout d&eacute;buta en l'an 1069. Dans les grandes villes d'Ascalon affluaient  des mercenaires des quatre coins du monde. Des centaines de recrues se  pr&eacute;sentaient &agrave; l'acad&eacute;mie, peu &eacute;taient assez braves pour surmonter les  tests. Mais lors des &eacute;preuves, un jeune nain se distingua parmi la  masse. Il ne le savait pas encore mais ses actes resteraient grav&eacute;s  dans l'histoire. Son nom &eacute;tait Shining Boudha, et &agrave; l'&eacute;poque, il &eacute;tait  dans une guilde v&eacute;n&eacute;rant &Eacute;ole,le dieu du vent.<br />
Au m&ecirc;me moment, un autre moine arrivait &agrave; Rin. Il venait de l'archipel  des &Icirc;les de Feu. Il s'entra&icirc;na lui aussi, les forces du roi n'ayant  jamais trop de moines.<br />
<br />
Et puis virent les Charrs. En Ascalon, ils ravag&egrave;rent les terres  autrefois fertiles en d&eacute;clenchant une pluie de flammes et de cristaux.  Ils d&eacute;truisirent l'arm&eacute;e d'Orr,et pouss&egrave;rent le royaume &agrave; la  destruction. La Kryte ne fut sauv&eacute;e que par l'intervention des  Invisibles, qui prirent ensuite le pouvoir par le biais du  Blanc-Manteau. De nombreux ascaloniens survivants travers&egrave;rent alors  les Cimefroides en guerre pour rejoindre ce pays,qui semblait &ecirc;tre la  derni&egrave;re contr&eacute;e s&ucirc;re pour les humains.<br />
<br />
Dans un baraquement de fortune pas loin de Diessa, Shining Boudha se  r&eacute;veilla. Il faisait nuit noire, la bise laissait danser les derni&egrave;res  flammes des torches quand soudain l'une d'entre elle attira son regard  fatigu&eacute;. A mesure qu'il &eacute;carquillait les yeux, le foyer de la torche  semblait former un signe runique &eacute;trange. Le jeune homme ne comprenait  pas le langage des runes, et pourtant une fois que ses yeux se pos&egrave;rent  dessus, un son sortit de sa bouche sans qu'il y eu m&ecirc;me song&eacute;: <br />
&laquo; - Baal... &raquo; <br />
La seconde qui suivit, il sombra dans un profond sommeil. Lorsqu'il se  r&eacute;veilla, il savait que Baal le tr&egrave;s haut, repr&eacute;sentant le pouvoir uni  des 5 divinit&eacute;s s'&eacute;tait adress&eacute; &agrave; lui pendant la nuit. Shi quitta &Eacute;ole  en initi&eacute; et ami; fait du hasard ou proph&eacute;tie, peu de temps apr&egrave;s il  rencontra Dark Boudha,qui semblait aussi avoir re&ccedil;u ce signe &eacute;trange .  Les deux hommes se mirent en qu&ecirc;te d'un futur lieu de rassemblement  pour ce qui allait devenir la grande guilde des Disciples de Baal .<br />
<br />
Le bastion de la r&eacute;sistance contre les Charrs leur offrit leurs  premi&egrave;res alliances. Miss Azerty, une &eacute;l&eacute;mentaliste exp&eacute;riment&eacute;e et  solitaire accepta de se joindre &agrave; eux. Un feu et un long r&eacute;cit  r&eacute;ussirent &agrave; raviver le courage d'affronter les fl&eacute;aux qu'elle n'avait  pu vaincre par le pass&eacute;. Mais les moines savaient qu'il fallait  &eacute;galement assurer la rel&egrave;ve en recrutant de jeunes combattants qui  sauraient apporter fougue et &eacute;nergie &agrave; leur communaut&eacute;. Ce f&ucirc;t le cas  avec Fr&egrave;re Teck qui saurait suivre l'enseignement des Boudhas et les  seconder dans leur qu&ecirc;te. Ce dernier &eacute;tait accompagn&eacute; d'un autre  &eacute;l&eacute;mentaliste, Elendil Paroski que Miss Azerty sut prendre sous son  aile. Rapidement, la difficult&eacute; des combats amena le petit groupe &agrave;  enr&ocirc;ler de fines lames qui pourraient retenir les crocs et les griffes  des entit&eacute;s monstrueuses qui croiseraient leur route, laissant ainsi le  temps &agrave; la magie &eacute;l&eacute;mentaire de br&ucirc;ler leurs chairs inf&acirc;mes. De  valeureux guerriers se pr&eacute;sent&egrave;rent &agrave; eux, mais deux retinrent  l'intention des Boudhas. Affaken Taeldred , combattant &eacute;m&eacute;rite &agrave;  l'esprit sage, qui sillonnait lui m&ecirc;me les routes de Tyrie depuis de  nombreuses ann&eacute;es &agrave; la recherche de ceux qui sauraient l'&eacute;pauler dans  sa qu&ecirc;te de sagesse. Vint plus tard Mao Yong, jeune guerrier agile venu  des terres de l'est dont l'humilit&eacute; se montra maintes fois r&eacute;demptrice.<br />
<br />
Les disciples travers&egrave;rent les Cimefroides pour rejoindre les r&eacute;fugi&eacute;s  en direction de la Kryte. Dans une auberge naine des Gorges de Grooble,  Shi remarqua un jeune &eacute;l&eacute;mentaliste, talentueux apparemment, car il  arrivait a faire chauffer son vin sans faire &eacute;clater le bock (  promis,c'est super difficile ). Son nom &eacute;tait Glory Haru, et il se  joignit &agrave; eux.<br />
<br />
La Kryte vacillait face aux hordes de mort-vivants, mais ses habitants  accueillirent avec joie les r&eacute;fugi&eacute;s qui fuyaient Ascalon et ses  Charrs. L'Arche du Lion leur apporta encore du renfort sous la forme  d'une autre jeune &eacute;l&eacute;mentaliste, The Janes Girl, qui se joignit &agrave; eux  pour sauver le dernier royaume humain des servants maudits de la liche. <br />
<br />
Leur croisade contre le mal les mena jusqu'au plus profond de la jungle  de Maguuma, o&ugrave; ils pactis&egrave;rent avec la Lame Brillante, et arriv&egrave;rent  jusqu'&agrave; temps pour voir le Cromlech de Denravi attaqu&eacute; par la  Blanc-Manteau. A leur arriv&eacute;e &agrave; la Clairi&egrave;re de l'Aurore, alors que les  disciples de Baal pr&eacute;paraient la bataille contre les fanatiques des  Invisibles, Glory reconnut deux de ses anciens condisciples de Nolani,  deux autres &eacute;l&eacute;mentalistes pr&ecirc;ts &agrave; les aider. Ils se nommaient Zen  Furious et Gram Lancefeu.<br />
<br />
Il leur fallu alors chasser le mal qui s&eacute;vissait dans le d&eacute;sert de  Cristal. Face &agrave; ces nouveaux risques, ils avaient besoin de nouveaux  talents. Prince des T&eacute;n&egrave;bres, un n&eacute;cromant aux pouvoirs &eacute;tranges retint  leur attention. Tandis que certains racontaient volontiers leurs  exploits aussi rocambolesques qu'improbables pour se faire mousser, ce  dernier &eacute;tait isol&eacute;, silencieux, et semblait ressentir l'ampleur du mal  qui s&eacute;vissait. Les deux moines discut&egrave;rent avec lui; il leur expliqua  alors les avantages que pourraient apporter sa science de la mort, et  son contr&ocirc;le des serviteurs. Ragaillardis par la venue de ce nouveau  compagnon, ils embarqu&egrave;rent vers le d&eacute;sert qu'ils eurent t&ocirc;t fait de  nettoyer de son mal sans que ne cesse de luire &agrave; aucun moment la flamme  dans leurs yeux.<br />
<br />
Brill le grand Dragon, sage entit&eacute; des temps anciens ne put que  s'incliner face &agrave; la force restaur&eacute;e de Baal. Il su percevoir qu'il  s'agissait l&agrave; des &eacute;lus, sauveurs annonc&eacute;s de la Tyrie. Il leur r&eacute;v&eacute;la  alors quel tragique destin les attendait : la force des Mursaats, la  trahison de la Liche, le poids de la corruption. Shining Boudha et Dark  Boudha comprirent alors qu'il leur faudrait s'adjoindre de nouveaux  alli&eacute;s et partirent vers les hautes Cimefroides &agrave; la recherche de  valeureux mercenaires. Sur ces sommets aux neiges &eacute;ternelles, ils  firent la rencontre improbable de deux femmes dont la douceur n'avait  d'&eacute;gal que leur fureur au combat. Les deux moines comprirent rapidement  que Jessy Cat l'intr&eacute;pide et Venus Nemesis la r&ocirc;deuse leur  apporteraient le talent et la hargne suffisante pour vaincre. Ils  purent alors traverser la mer vers les terribles &icirc;les de feu gr&acirc;ce &agrave;  l'aide des nains dont ils avaient acquis le respect dans les combats  acharn&eacute;s qu'ils avaient livr&eacute; dans les montagnes.<br />
<br />
Ces &icirc;les volcaniques dissimulaient la racine du mal rongeait la Tyrie.  Les Mursaats qui gardaient la Porte de Komalie &eacute;taient vaincus, et la  Liche l&acirc;chait sur le monde les pires cr&eacute;atures venues d'un royaume de  cauchemar, les Titans. Mais les vaillants disciples donn&egrave;rent vie aux  proph&eacute;ties de Baal, et l'affront&egrave;rent au sommet du plus haut volcan de  l'archipel, sur la pierre de sang. L'immonde mort vivant fut banni du  monde des humains, scell&eacute; &agrave; jamais dans un lieu d'o&ugrave; il ne ressortirait  jamais.<br />
<br />
Vint alors le temps de l'amusement et des d&eacute;fis. La liche morte les  valeureux guerriers se mirent en qu&ecirc;te de nouveaux d&eacute;fis, la guerre  &eacute;tait finie mais l'Outremonde et la fissure restaient infest&eacute;es  d'esprits en tout genre ayant fuit le monde des vivants face &agrave; la force  des disciples. La joyeuse guilde pouvaient passer d'un monde &agrave; l'autre  gr&acirc;ce au pouvoir de Balthazar et &agrave; celui de Grenth, afin de chasser ces  cr&eacute;atures d&eacute;moniaques et de les d&eacute;pouiller d'autant d'objet pr&eacute;cieux.  Mais &agrave; cette &eacute;poque, leur loisir principal &eacute;tait la chasse au nain. Ils  avaient d&eacute;couvert un spot pr&egrave;s de Droknar o&ugrave; les petits hommes chevelus  et barbus se d&eacute;multipliaient sans cesse. Ce lieu dont tout le mal qui  avait envenim&eacute; la Tyrie &eacute;tait issu faisait trembler toute personne  saine d'esprit &agrave; la simple prononciation de son nom: la Fournaise des  Lamentations. Les Disciples de Baal y voyaient plut&ocirc;t le lieu id&eacute;al  pour se laisse aller &agrave; la d&eacute;bauche et &agrave; la barbarie gratuite. Ils  allaient vider les tonneaux de bi&egrave;re, d&eacute;pouiller les nains de leurs  armes forg&eacute;es dans la lave la plus chaude, les ridiculiser &agrave; coups de  croche-pattes, de cocos et de &laquo; je te tiens, tu me tiens par la  barbichette &raquo;.<br />
<br />
Mais tant de bonheur ne pouvait durer. Alors que les disciples se  grillaient quelques minotaures &agrave; la sauce aux iris rouge au coin du  feu, chantant &agrave; la gloire de Baal et surtout &agrave; celle des tonneaux de  bi&egrave;re, ils virent arriver une sorte de bip&egrave;de boursoufl&eacute;, proche d'un  Cynok, gesticulant et g&eacute;missant. Alors que les Boudha tentaient de se  lever afin de pr&eacute;venir toute attaque, l'immonde forme tombait au sol,  tu&eacute;e par un homme d'aspect fort respectable et au bord de l'&eacute;puisement,  un d&eacute;nomm&eacute; Togo. Les Boudha ayant perdu l'&eacute;quilibre, ils demand&egrave;rent &agrave;  leur disciples de s'occuper de leur h&ocirc;te et d&eacute;cid&egrave;rent de se reposer,  leur instinct leur commandant d'&eacute;viter de continuer leur beuverie pour  vivre au mieux la longue journ&eacute;e qui les attendrait le lendemain. Cette  cr&eacute;ature annon&ccedil;ait un retour du mal et des tueries, ce qui n'&eacute;tait pas  sans r&eacute;jouir les combattants qui commen&ccedil;aient &agrave; se lasser de taper sur  plus petit qu'eux.</p>
<p><strong>Chapitre second: Shiro la fiote</strong><br />
  <br />
  Le lendemain matin, alors que Jess pr&eacute;parait le caf&eacute;, Fr&egrave;re les toasts  et que Dark finissait les tonneaux, Shi s'approcha de leur h&ocirc;te et le  r&eacute;veilla en ces termes:<br />
  &laquo;- Dis donc le plouc, c'est pas un h&ocirc;tel ici, donc soit tu l&acirc;che les PO  soit je te vire &agrave; coups de pieds au cul, en plus tu pue le poisson &raquo;.<br />
  Le prince Togo &agrave; peine remis de son voyage n'oubliait pas sa mission et demanda de l'aide aux disciples:<br />
  &laquo;- Pardon jeune moine brillant, mais votre aide me serait pr&eacute;cieuse. Un  groupe de vaillants guerriers comme vous ne peut que conna&icirc;tre le grand  Menhlo, le sauveur de la Tyrie &raquo;.<br />
  Ces propos restaur&egrave;rent la joie dans la guilde, provoquant un fou rire  g&eacute;n&eacute;ralis&eacute; que m&ecirc;me les plus important maux de cr&acirc;ne ne surent contenir.<br />
  &laquo;- L'autre guignol l&agrave;! C'est vrai qu' heureusement qu'il &eacute;tait l&agrave; celui  l&agrave;, sinon la liche n'aurait pu tuer personne. Eh ben si c'est ton seul  espoir t'es vraiment dans la merde bonhomme. Mais si tu cherche les  vrais h&eacute;ros de Tyrie ils sont l&agrave; devant toi, je savais bien qu'on  aurait du d&eacute;poser des droits, enfin bon, r&eacute;torqua Shi.<br />
  - Des ivrognes et un nain, mais c'est impossible, dit alors Togo la mine d&eacute;confite.<br />
  - Reste poli sinon tu va voir mon cr&acirc;ne de tr&egrave;s pr&egrave;s toi, lui assena le nain.<br />
  - Et si tu ne nous croit pas tu peux aller voir Brill, le dragon immortel, il te confirmera nos dires, ajouta Dark.<br />
  - Euh patrons, le Brill je crois qu'on lui a trop tap&eacute; dessus, et on arrive plus &agrave; le r&eacute;veiller, avoua Frerot &raquo;<br />
  - Bon,&eacute;coute moi bien le plouc, si tu compte sur Menhlo pour te  soigner, saute tout de suite de la falaise, &ccedil;a ira plus vite. Quand &agrave;  Cynn, elle est m&ecirc;me pas foutu de cibler. Et Devona, certes elle se  bagarre pas mal, mais elle prend plus de coups qu'elle n'en donne. Si  ta mission est importante, &eacute;vite ces bouseux et parle moi en,trancha  Shi.<br />
  - Mais qui me dit que vous ne combattez pas pour le mal? je ne  partirais pas sans Menhlo, que ce soit avec ou sans vous, r&eacute;torqua Togo.<br />
  - Bon, que quelqu'un me ram&egrave;ne cette fillette de Menhlo, ensuite on  embarque pour ton pays, mais juste parce qu'on a besoin de se  d&eacute;rouiller! Et bordel que Dark laisse ces tonneaux tranquilles,  s'emporta Shi.&raquo;.<br />
  <br />
  Menhlo, Cynn et Devona dans la soute , la joyeuse guilde s'en va en  compagnie de Togo pour r&eacute;gler les d&eacute;sordres de Cantha. A peine eurent  ils d&eacute;barqu&eacute; au centre de Kaineng que Miss Azerty reconnu une de ses  anciennes acolytes en la personne de Bald Inette, avec laquelle elle  avait plus jeune l'habitude d'organiser quelques tueries entre deux  soir&eacute;es chaudes. Miss expliqua &agrave; la guilde qu'il serait opportun que  Bald les accompagna plut&ocirc;t que de se fier &agrave; ce Togo ou &agrave; Menhlo dont on  connaissait la valeur.<br />
  &laquo;- Vous avez besoin d'aide? Je suis votre homme. Enfin, fa&ccedil;on de  parler, quoi! Au fait, il y a des primes d'int&eacute;ressement quand on bosse  pour Togo? &raquo;<br />
  Forte d'un nouveau membre, la guilde prit alors la route en suivant Togo &agrave; la recherche du mal qui rongeait ce continent.<br />
  <br />
  Les routes &eacute;taient effectivement infect&eacute;es de ces cr&eacute;atures  boursoufl&eacute;es dont ils purent rapidement apprendre qu'elles furent  autrefois des hommes, mais qu'elles &eacute;taient &agrave; pr&eacute;sent rong&eacute;es par un  mal dont l'origine n'&eacute;tait pas certaine. Les disciples rencontr&egrave;rent  &eacute;galement un nouveau type de guerrier : les assassins. Les premiers  qu'ils rencontr&egrave;rent r&eacute;ussirent presque &agrave; tromper la vigilance des  Boudhas par la rapidit&eacute; et la puissance de leurs attaques. Mais ces  derniers avaient les d&eacute;fauts de leurs qualit&eacute;s, leur vitesse impliquait  un corps certes vif, mais fr&ecirc;le, et finalement un bon m&eacute;t&eacute;ore et on en  parlait plus. Ce qui d'ailleurs ravissait Bald qui prenait un malin  plaisir &agrave; utiliser leur corps pour constituer de v&eacute;ritables arm&eacute;es  d'horreurs en tout genre, tout en effrayant les honn&ecirc;tes citoyens.  Malgr&eacute; ces rencontres souvent d&eacute;sagr&eacute;ables avec ces malandrins, il en  fut un qui attira l'attention des Boudhas par son sens de l'honneur.  C'est ainsi que Zarraki Kenpatchi se joignit &agrave; la bande.<br />
  <br />
  Mais dans les d&eacute;tours de Kaineng, on se perd facilement. Il fallait au  disciples un guide dans ces ruelles. Zarraki leur proposa une jeune  ritualiste qu'il avait connu &agrave; Shing Jea.<br />
  &laquo;- Je peux vous la pr&eacute;senter: c'est une de mes anciennes &eacute;l&egrave;ves,  expliqua Togo. Elle &eacute;tait tr&egrave;s prometteuse, mais elle a quitt&eacute; le  mona...<br />
  - On s'en tape de &ccedil;a, elle habite o&ugrave; et elle fait quoi en ce moment? L'interrompit Dark.&raquo;<br />
  Le trajet jusqu'&agrave; Waijun se fit sans encombres, mis &agrave; part Menhlo qui  n'arr&ecirc;tait pas de se plaindre et qu'il fallut calmer d'un coup de  tonneau. Il arriv&egrave;rent devant le manoir familial des Ninghen Io. Une  jeune femme blonde en sortit.<br />
  &laquo;- Ne vous inqui&eacute;tez pas, elle m'adore, commen&ccedil;a Togo avant de se  tourner vers la ritualiste, Ah! Kiala, que je suis heureux de te  revoir! Voila,je voulais te parler et...<br />
  - Si tu crois que je vais te suivre dans tes conneries, vieux bouc, tu  peux te mettre le doigt dans l'oeil: je sais tr&egrave;s bien dans quelle  merdes tu veux m'entra&icirc;ner ! Et quand &agrave; vous, vous feriez mieux de le  laisser tomber,c'est un aimant a ennuis ce type. Mais malgr&eacute; tout,je  peux pas laisser partir Zak avec ce guignol. Je vous accompagne.<br />
  <br />
  Togo louait les dieux d'avoir mis ces guerriers sur sa route. En  quelques jours il en apprit plus sur le mal qui infectait son royaume  qu'en plusieurs dizaines d'ann&eacute;es. Il pu en effet comprendre que Shiro,  l'ancien bodyguard de l'empereur, tentait de revenir du royaume des  morts. Togo expliqua aux disciples de quelle mani&egrave;re le mal avait  envahi Shiro autrefois, faisant de lui une b&ecirc;te sanguinaire, mais  surtout &agrave; quel point ils avaient du lutter pour l'emp&ecirc;cher de r&eacute;pandre  la douleur en Cantha. Mais pour le moment, Shiro n'&eacute;tait qu'un esprit,  et pour tuer un esprit, il faut &ecirc;tre un esprit. Ou Weh No Su,&ccedil;a marche  aussi. Un type avec un chapeau &eacute;trange leur annon&ccedil;a que pour l'&ecirc;tre,  ils devaient tuer les c&eacute;lestes lors d'une &eacute;preuve rituelle dans un  quartier louche. C'est ainsi qu'ils rencontr&egrave;rent Jeremine Moniale, une  petite moinette qui avait aussi r&eacute;ussi l'&eacute;preuve. Et un moine de  plus,un!<br />
  <br />
  Shining Boudha dit alors &agrave; Togo que le bonhomme paraissait tout &agrave; la  port&eacute;e de ses guerriers. Mais le vieux ne semblait pas de cet avis, de  plus ils ne pouvaient rien faire tant que Shiro ne se montrait pas. Il  leur expliqua que le mieux &agrave; faire en attendant &eacute;tait de sympathiser  avec une des grandes ethnies de Cantha, les Luxons ou les Kurzicks.  Dr&ocirc;le d'histoire que celle qui opposait ces deux peuples depuis des  si&egrave;cles, mais l&agrave; n'est pas le sujet.<br />
  Shi d&eacute;cidera que la guilde infiltrerait les Kurzicks. Dark demanda pourquoi le choix ne se porterait pas sur les luxons.<br />
  &laquo; - Tu veux qu'on fasse quoi sur une plage o&ugrave; la mer ne bouge pas,  rigolo? Retourne chasser tes &eacute;lites et laisse moi r&eacute;fl&eacute;chir. &raquo;<br />
  Les Kurzicks pr&eacute;sentaient en effet de nombreux avantages: ils ne  sentaient pas le poisson, ils ne vivaient pas sur le dos de tortues  g&eacute;antes et ils avaient m&ecirc;me des b&acirc;timents en dur. Une fois les reliques  de leur saint sauv&eacute;es,et le Verger &eacute;ternel en s&eacute;curit&eacute;, les Kurzicks  furent des alli&eacute;s valeureux. Ainsi, aux pieds des grands arbres  d'Echowald, ils rencontr&egrave;rent un jeune noble orphelin, Lord Grimjow. Ce  dernier connaissait la for&ecirc;t comme sa poche, et il guida les disciples  jusqu'au eaux endormies, o&ugrave; il fit ses preuves en aidant les disciples  &agrave; vaincre le Grand Dragon.<br />
  <br />
  Le temps pressait et il fallait &agrave; nos h&eacute;ros apprendre aupr&egrave;s du  Kuunavang comment vaincre Shiro. Mais pour cela il fallait encore  lib&eacute;rer ce dernier du joug du ma&icirc;tre assassin. Finalement si les  dragons sont impressionnant et s'ils parlent beaucoup de leur force,  leur faiblesse n'a d'&eacute;gal que leur vantardise. Ainsi ce dernier fut  vaincu et appris alors aux disciples &agrave; faire appel au pouvoir supr&ecirc;me.<br />
  La guilde reprit la direction du palais afin de sauver l'empereur. En  effet il fallait &agrave; Shiro le sang du descendant de celui qui l'avait  maudit afin de retrouver sa place dans le monde des vivants. Les  Boudhas et leurs compagnons arriv&egrave;rent juste &agrave; temps pour &eacute;pargner  l'empereur, mais ils avaient oubli&eacute; un d&eacute;tail, Togo &eacute;tait lui aussi de  sang royal, et Shiro avait r&eacute;ussi sa diversion. Togo &eacute;tait mort, Shiro  &eacute;tait de retour.<br />
  <br />
  Il fallait donc trouver une strat&eacute;gie, car nombreux &eacute;taient les groupes  qui se prenant pour des h&eacute;ros s'approchaient de Shiro pour se mesurer &agrave;  lui, mais tous sans exception p&eacute;rissaient.<br />
  Apr&egrave;s plusieurs heures de conciliabule, les disciples pens&egrave;rent avoir  trouver la solution. Finalement les d&eacute;bats sont bien souvent utiles.  Certains propos&egrave;rent plusieurs groupes, des diversions, un si&egrave;ge, faire  appel aux dieux, tout f&ucirc;t envisag&eacute;, mais une seule solution f&ucirc;t  retenue. Les Boudhas, las des discussions et conscient de l'urgence,  s'exclam&egrave;rent dans toute leur sagesse:<br />
  &laquo;- On fonce dans le tas, on lui balance tout ce qu'on a dans le ventre  sur la tronche et on verra bien ce qu'il vaut le Shiro. Merde apr&egrave;s  tout c'est juste un assassin et le carton &agrave; l'&eacute;poque n'&eacute;tait pas plus  solide que maintenant &raquo;.<br />
  <br />
  Et &eacute;trangement, les plans les plus simples marchent parfois: Shiro fut  banni,cette fois dans un lieu dont &icirc;le ne pourrait jamais sortir. Baal  venait encore de donner la victoire &agrave; ses disciples, une victoire  c&eacute;l&eacute;br&eacute;e dans tout l'empire.</p>
<p><strong>Chapitre 3: D&eacute;mons et merveilles</strong><br />
  <br />
Avec Shiro vaincu, l'affliction stopp&eacute;e et les arm&eacute;es d'afflig&eacute;s et de  shiro'ken mises en d&eacute;route, il semblait que les disciples pouvaient  enfin prendre des vacances. Shi proposa la Citadelle de Granite,une  fameuse station de ski, Bald voulait leur faire d&eacute;couvrir les soir&eacute;es  endiabl&eacute;es de Kaineng, Jess d&eacute;sirait retourner en Ascalon, Affa aurait  pr&eacute;f&eacute;r&eacute; un camping dans la Vall&eacute;e Oubli&eacute;e, Kiala pensait &agrave; la bronzette  au lagon d'Haiju. Mais ce fut Dark qui eut le dernier mot:<br />
&laquo; - Mais vous &ecirc;tes tous malades! On va attraper la cr&egrave;ve &agrave; la  montagne,Ascalon c'est vide, Kaineng c'est moche, l'Outremonde c'est  trop dangereux et Shing Jea c'est chiant! Moi je vous dit qu'on prend  le premier bateau pour Kamadan et qu'on va aller se dorer la pilule,  sous le soleil des tropiques! &raquo;<br />
Personne n'osa contester ces paroles pleines de sagesse,et la troupe embarqua gaiement sur le navire en partance pour Elona.<br />
<br />
Les disciples d&eacute;chant&egrave;rent vite une fois arriv&eacute;s &agrave; Kamadan.  l'atmosph&egrave;re &eacute;tait lourde, les gens tristes et inquiets. Un certain  nombre d'&eacute;v&egrave;nement faisaient craindre le pire. Baal intervint alors  aupr&egrave;s de ses Boudhas afin qu'ils prennent la juste mesure du combat  qui les attendait. Il n'aurait pas l&agrave; &agrave; vaincre un assassin eff&eacute;min&eacute; ni  un mage mal intentionn&eacute;, et sans pouvoir leur en dire plus le dieu de  la mort leur f&icirc;t comprendre qu'ils allaient affronter le mal en  personne. Les disciples s'organis&egrave;rent rapidement. Seuls, ils n'y  arriveraient pas c'est ainsi qu'ils d&eacute;cid&egrave;rent d'envoyer un des leurs &agrave;  la recherche de combattants qui pourraient accompagner la guilde dans  leur qu&ecirc;te. Fr&egrave;re Teck, qui depuis longtemps voulait prouver &agrave; ses  ma&icirc;tres Boudhas que leur enseignement avait port&eacute; ses fruits, se porta  volontaire. Il devrait trouver une dizaine de guerriers dont il aurait  la responsabilit&eacute; de former &agrave; l'esprit de Baal. Pendant ce temps les  autres disciples pr&eacute;pareraient un solide plan d'attaque.<br />
<br />
Mais Dark ne l'entendait pas de cette oreille, il ne ferait rien de  plus sans go&ucirc;ter les d&eacute;lices du palet qui se servaient en cette  contr&eacute;e. Il se dirigea vers la premi&egrave;re auberge venue et remarqua  aussit&ocirc;t une moine chauve, titubant et qui r&acirc;ler sans cesse sur le  manque de professionnalisme des guerriers, que ces derniers ne juraient  plus maintenant que par leur allure, qu'ils s'attiraient tous les  honneurs sans jamais remercier ceux qui au fond donnaient la victoire:  les moines. Il jurait qu'on ne l'y verrait plus &agrave; soigner tous ces  malotrus sans reconnaissance. Dark se dit qu'un confr&egrave;re qui comme lui  &eacute;tait amateur de la bonne boisson ne pouvait avoir &eacute;t&eacute; mis sur sa route  que par Baal.<br />
&laquo; - Que la bi&egrave;re coule &agrave; flots pour moi et mon ami! s'exclama-t-il.<br />
- Moi c'est Malar le fauve, bourricot! r&eacute;pondit l'acolyte.&raquo;<br />
Compl&egrave;tement ivres,les deux comp&egrave;res d&eacute;clench&egrave;rent une bagarre g&eacute;n&eacute;rale  dans l'auberge. Les disciples se port&egrave;rent au secours des deux moines,  debout sur le comptoir, qui tentaient de contenir une bande de  guerriers v&ecirc;tus d'armures de mauvais go&ucirc;t. Les Lanciers du Soleil  intervinrent rapidement,encerclant l'auberge.<br />
&laquo; - Rendez vous! Vous &ecirc;tes cern&eacute;s! ordonna le chef des Lanciers.<br />
- Pour un premier rendez-vous,c'est un peu brutal, plaisanta Kiala.<br />
- On ne rigole pas, rendez vous, ou sinon...<br />
- Ou sinon quoi? lan&ccedil;a Shi , t'as l'air fin &agrave; donner des ordres en jupe toi!<br />
- Ou sinon on attaque, &agrave; 50 contre 10, vous faites moins les malins l&agrave;, hein?<br />
- M&Ecirc;ME PAS PEUR! Hurl&egrave;rent les disciples en lan&ccedil;ant des chopes sur les forces de l'ordre. &raquo;<br />
<br />
Une femme intervint pour calmer le jeu.<br />
&laquo; - Je suis Kormir, mar&eacute;chale des Lanciers du Soleil. Vous &ecirc;tes en &eacute;tat  d'arrestation. Mais nous avons besoin d'hommes et de femmes capables  d'attaquer Varesh Ossa dans sa forteresse de Gandara.<br />
- C'est pay&eacute; combien, demanda Bald,int&eacute;ress&eacute;e.<br />
- Vous plaisantez ?!<br />
- Hahaha! Et si on refuse, lan&ccedil;a Dark &agrave; Kormir, apparemment d&eacute;confite.<br />
- Si vous refusez, vous en avez pour 10 ans &agrave; casser des cailloux dans les carri&egrave;res de Dohjok.<br />
- On pourrait aussi tuer tous vos jolis soldats en jupette, vous sacrifier &agrave; Baal et rejoindre cette Varesh,non? ironisa Shi.&raquo;<br />
C'est ainsi que les disciples obtinrent une somme assez cons&eacute;quente,  une grande quantit&eacute; de bi&egrave;res et un voyage aller-retour pour Gandara.  Sur place,ils furent le fer de lance de l'attaque des Lanciers,m&ecirc;me si  ils ne prenaient pas &ccedil;a tr&egrave;s au s&eacute;rieux . Ce ne fut que lorsqu'ils  arriv&egrave;rent devant Varesh qu'ils prirent totalement conscience de la  gravit&eacute; de la situation: le dieu mal&eacute;fique de Varesh se manifesta et  obligea les disciples &agrave; se replier. Ils vol&egrave;rent un bateau et vogu&egrave;rent  jusqu'au c&ocirc;tes kournanes. L&agrave;-bas,ils rejoignirent un campement des  lanciers b&acirc;ti dans une immense grotte. de nombreux combattants s'y  reposaient, mais on comptait de nombreux bless&eacute;s.<br />
<br />
Frero, arpentant le camp &agrave; la recherche de vaillants combattants,  rencontra une &eacute;l&eacute;mentaliste au port noble, Aramina del Wyldred. Elle  venait d'Ascalon ,et elle aussi, elle avait v&eacute;cu le cataclysme de la  Fournaise, et aujourd'hui elle partageait ses connaissances avec  d'autres &eacute;l&eacute;mentalistes. Elle &eacute;tait accompagn&eacute;e d'une n&eacute;cromante  krytienne ,Talia Marana, dont les parents avaient &eacute;t&eacute; des h&eacute;ros de la  lutte contre les Charrs aux cot&eacute;s de Sa&uuml;l. Non loin, une autre jeune  &eacute;l&eacute;mentaliste nomm&eacute;e Saffi Erikdotter &eacute;coutait avec attention les  le&ccedil;ons d'Aramina. Elles ne furent pas difficiles &agrave; convaincre,car la  haine qu'elles avaient pour Varesh et ses d&eacute;mons n'avait d'&eacute;gal que  leur envie de voir du pays. C'est ainsi que les disciples accueillirent  trois nouvelles recrues.<br />
<br />
Poursuivis par l'arm&eacute;e kournane et ses d&eacute;mons affam&eacute;s, les disciples  s&eacute;curis&egrave;rent leur nouvelle base et commenc&egrave;rent &agrave; lancer des attaques  sur les garnisons dispers&eacute;es sur la c&ocirc;te. Un jour, alors qu'ils  d&eacute;truisaient une base de l'arm&eacute;e,ils trouv&egrave;rent deux hommes dans une  ge&ocirc;le infecte: deux &eacute;l&eacute;mentalistes captur&eacute;s par les soldats de Varesh  et promis &agrave; une ex&eacute;cution sommaire et arbitraire, Elun Dil et Maco  l'Indiscret. Ils rejoignirent ainsi les rangs de l'arm&eacute;e de Baal,  apportant une puissance de feu suppl&eacute;mentaire aux disciples. <br />
<br />
Mais pour vaincre Varesh, un vieux n&eacute;cromant d&eacute;cr&eacute;pit qui se faisait  passer pour un espion leur raconta qu'il faudrait lib&eacute;rer Kormir et  tuer la S&egrave;cheresse, un d&eacute;mon hideux qui mena&ccedil;ait de d&eacute;vorer un fleuve.  Les disciples,qui commen&ccedil;aient &agrave; savoir comment vaincre des d&eacute;mons  s'occup&egrave;rent de ce dernier, mais s'infiltrer dans Gandara demandait  plus que de la force. Par chance, Baal aidait ses disciples, et pla&ccedil;a  une jeune r&ocirc;deuse sur leur chemin, Kiara Shandris. Gr&acirc;ce &agrave; elle, ils  purent d&eacute;jouer la vigilance des arm&eacute;es de Varesh et lib&eacute;rer la  mar&eacute;chale.<br />
<br />
La prochaine &eacute;tape du plan &eacute;tait de se rendre &agrave; Vabbi pour convaincre  les princes de se joindre &agrave; eux dans la lutte contre le Cr&eacute;puscule. Il  fallait passer par un labyrinthe de grottes mal fr&eacute;quent&eacute;es, notamment  par des corsaires tr&egrave;s rapides et un d&eacute;mon mal embouch&eacute;. La  routine,quoi. Ils se rendirent &agrave; Kodash,la plus grande ville de la  r&eacute;gion pour s'y ravitailler. Au hasard d'une ruelle mal fam&eacute;e,ils  tomb&egrave;rent face &agrave; des coupeurs de bourses,des d&eacute;trousseurs qui &eacute;taient  plus habitu&eacute;s &agrave; d&eacute;trousser des marchands gras que des h&eacute;ros aguerris.  Mais une guerrier leur sauta furtivement dessus et les massacra tous &agrave;  coup de hache.<br />
&laquo; - On pouvait se d&eacute;brouiller seuls,plaisanta Malar.<br />
- Ils me devaient de l'argent, je suis rembours&eacute;e maintenant, r&eacute;pondit  la jeune guerri&egrave;re en fouillant les corps &agrave; la recherche d'objets  pr&eacute;cieux.<br />
- Tu m'est sympathique, petite, lan&ccedil;a Shi avant de se rendre compte  qu'il lui arrivait au niveau de la poitrine, comment t'appelles-tu?<br />
- Mon nom est Hache de Jade.<br />
- Et que dirais-tu de te joindre &agrave; nous? Proposa Frero. &raquo;<br />
Elle accepta avec joie.<br />
<br />
Le reste de Vabbi fut monotone en comparaison: se bourrer la gueule et  vaincre Lumo en duel de mime au festival de Lyss, s'infiltrer dans un  coffre au tr&eacute;sor g&eacute;ant pour ramener deux des princes morts de trouille,  d&eacute;fendre un fort attaqu&eacute; par des margonites, reprendre un temple  flottant des mains des d&eacute;mons, bref, un bonne grosse partie de plaisir.  Mais la suite allait se r&eacute;v&eacute;ler plus dure: pour attaquer Varesh et son  dieu mal&eacute;fique,il faudrait se rendre &agrave; l'endroit o&ugrave; ce dernier avait  &eacute;t&eacute; vaincu: au milieu d'un d&eacute;sert g&eacute;ant intraversable par les vivants.  Ils durent d&eacute;livrer Palawa Joko, le Fl&eacute;au de Vabbi pour lui faire  cracher le morceau: comment peut faire un vivant pour traverser les  d&eacute;solations de souffre? La momie en d&eacute;composition leur r&eacute;pondit qu'il  fallait vaincre Aijundu et prendre le contr&ocirc;le des guivres Jurundus  pour traverser les sables mortels. Mais Aijundu &eacute;tait coriace, et il  leur fallait encore du renfort,quelqu'un qui connaissait son point  faible.<br />
<br />
Les disciples se reposaient &agrave; la porte de la d&eacute;solation, en compagnie  de centaures bourrus et d'&acirc;mes &eacute;gar&eacute;es. peu d'humains vivaient encore  si pr&egrave;s du d&eacute;sert. Mais un jour, un n&eacute;cromant attira leur attention. Il  paraissait compl&egrave;tement fou, et passait ses journ&eacute;es &agrave; fumer des  substances illicites en chantant &laquo;Hissez haut nos  couleurs,yo,ho,ho,l'&acirc;me des chevreuils jamais ne mourra! &raquo; et en jouant  de la guitare &agrave; 52 cordes. En se renseignant aupr&egrave;s des centaures, il  apparut que cet &eacute;trange personnage avait perdu sa famille dans ce  d&eacute;sert, et qu'il vivait ici depuis longtemps. Peut-&ecirc;tre savait-il  comment vaincre Aijundu,mais personne ne voulait s'en approcher. Ce fut  Kiala qui fit le premier pas:<br />
&laquo; - Salut! Tu fais tourner? <br />
- Tiens sister, tire un coup, c'est de la bonne.<br />
- Tu tra&icirc;nes ici depuis longtemps?<br />
- Way, mais je sais pas compter alors je peux pas dire combien de temps.<br />
- Tu saurais comment faire pour battre la guivre g&eacute;ante dehors?<br />
- Je connais son point faible: elle adore les sucres d'orges. Bonne chance,poup&eacute;e.&raquo;<br />
En effet, la reine des guivres adorait tellement les sucres d'orges que  les disciples purent sans mal s'en d&eacute;barrasser. Et pour remercier  Liviing Dead Beat, ils lui propos&egrave;rent de venir avec eux.<br />
<br />
Le trajet jusqu'au ruines de Morah fut difficile, essentiellement &agrave;  cause du manque de marchands d'alcool sur la route. Dark faillit  d&eacute;faillir quand on lui annon&ccedil;a qu'il faudrait attendre 8 jours sans une  goutte de rhum, de bi&egrave;re ou autre. Mais sur place, il n'y pensait d&eacute;j&agrave;  plus: Varesh, au milieu du crat&egrave;re, commen&ccedil;ait &agrave; invoquer son dieu  maudit. Les Boudhas,dans leur finesse habituelle, d&eacute;cid&egrave;rent que tout  &ccedil;a,c'&eacute;tait de la gnognotte, et que de toutes fa&ccedil;ons elle devait payer  pour ce qu'elle avait fait &agrave; Gandara. La technique qu'ils avaient mise  au point aurait fait baver Dunkoro: on fonce dans le tas et on tue.  C'est tout. Bizarrement, elle marcha tr&egrave;s bien, mais alors qu'ils  commen&ccedil;aient &agrave; repartir, Varesh se releva:<br />
&laquo; -  Aha je suis de retour,pour vous jouer un mauvais tour! Venez &agrave; moi, serviteurs d'Abbadon!<br />
- Rho l'enfoir&eacute;e! Hurla Shi. <br />
- Tu vas voir! L'invectiva Dark.<br />
- Diantre! S'exclama Jess.<br />
- Mille millions de mille sabords! Lan&ccedil;a Bald.<br />
- Oh la gueuse! Cria Affa.<br />
- Quelle emmerdeuse, lan&ccedil;a Saffi.<br />
- Nu ma nang! L&acirc;cha Kiala.<br />
- Saperlipopette, dit Aramina.<br />
- Calmez vous,on va se la faire, termina calmement Talia.&raquo;<br />
<br />
Apr&egrave;s 2 heures de combats acharn&eacute;, il semblait que les disciples  pouvaient sortir le barbeuk et se griller quelques saucisses sur le  cadavre de Varesh, mais sa mort entra&icirc;na les disciples dans l'antre  d'Abbadon, le royaume des d&eacute;mons, le tourment. Nos h&eacute;ros semblaient un  peu perdus l&agrave;-dedans. Un oubli&eacute; leur apprit qu'ils se trouvaient &agrave; la  porte du tourment, une des dix portes du royaume du tourment, l'un des  10 endroits surs dans se cauchemar.<br />
&laquo; - Mais o&ugrave; c'est qu'on est? demanda Shi. Au paradis des nains?<br />
- Mais non, on doit &ecirc;tre &agrave;... au... euh... dans ton cul peut &ecirc;tre, essaya Kiala.<br />
- Aaaaaah! Ce pilier ressemble &agrave; un humain! Cria Bald.<br />
- Mais je suis un humain, s'offusqua le pilier.<br />
- On se croirait dans un intestin g&eacute;ant, fit remarquer Talia.<br />
- T'es d&eacute;j&agrave; all&eacute; dans un intestin g&eacute;ant,toi? Demanda Dark.&raquo;<br />
<br />
Mais m&ecirc;me dans le royaume d'Abbadon, Baal leur fit parvenir une  nouvelle vision: ils devaient lib&eacute;rer les &acirc;mes prisonni&egrave;res des  margonites. Ils devaient pour cela se rendre &agrave; la porte de la douleur  o&ugrave; ils d&eacute;truisirent les driders qui gardaient les &acirc;mes pour le compte  de Dhumm. Ils devaient ensuite se rendre au temple des 6 dieux, pour y  d&eacute;truire les g&eacute;n&eacute;raux d'Abbadon. En chemin, ils rencontr&egrave;rent une  n&eacute;cromancienne, seule humaine dans un monde de d&eacute;mons. Son nom &eacute;tait  Sasia Danakei, et elle aussi voulait d&eacute;truire Abbadon. <br />
&laquo; - A plusieurs on y arrivera mieux, dit-elle.&raquo; <br />
Elle rejoint donc la joyeuse compagnie.<br />
<br />
Arriv&eacute;s &agrave; la porte de l'angoisse, ils se renseign&egrave;rent sur leurs  ennemis. Un &eacute;claireur des oubli&eacute;s leur annon&ccedil;a qu'ils devraient  affronter deux anciennes connaissances, la Liche,et Shiro Tagashi, tous  deux enferm&eacute;s dans le tourment. <br />
&laquo; - Heureusement,le carton n'est pas plus dur ici qu'ailleurs! Lan&ccedil;a Dark.&raquo; <br />
Et effectivement, bien que la bataille contre les Shiro Ken, les  Titans, les margonites, les d&eacute;mons et enfin les deux golios dans leur  temple maudit fut difficile et &eacute;puisante, les disciples sortirent  vainqueurs,et obtinrent la b&eacute;n&eacute;diction des cinq dieux. <br />
<br />
Ext&eacute;nu&eacute;s, bless&eacute;s, les disciples &eacute;taient parvenus &agrave; la derni&egrave;re des  portes du tourment. Mais il semblait qu'Abbadon se lib&eacute;rait de ses  cha&icirc;nes. Inspir&eacute;s par Baal, les deux Boudhas exhort&egrave;rent les disciples  &agrave; d&eacute;truire le dieu d&eacute;chu: &laquo; Aujourd'hui,on va rentrer dans la l&eacute;gende,  on va d&eacute;truire ce dieu de pacotille, on va sauver notre monde de ses  d&eacute;mons. Avec nous,les amis! &raquo; . La bataille qui suivit fut ensuite  cont&eacute;e dans nombre de l&eacute;gendes. Le pouvoir de Baal se d&eacute;cha&icirc;na contre  celui d'Abbadon, Dieu contre Dieu, humains contre d&eacute;mons. Lorsque enfin  le dieu des secrets tomba, Kormir utilisa la b&eacute;n&eacute;diction pour contenir  sa puissance. Les disciples avaient sauv&eacute; le monde, ils avaient tu&eacute; un  dieu, leur noms &eacute;taient d&eacute;sormais grav&eacute;s dans l'Histoire de la Tyrie.</p>
<p>Suite &agrave; venir ...</p>

<?php 
	include 'footer.php';
?>
